spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  datasource:
    url: jdbc:mysql://159.65.237.210:3306/chelfieme
    username: root
    password: Root?12345678
    driver-class-name: com.mysql.jdbc.Driver